// app/contact/page.tsx
// Contact page — assembles ContactForm + ContactInfo sections.
// This is a Server Component (no "use client") — the child
// components handle their own client-side state.

import type { Metadata } from "next";
import ContactForm from "@/components/ContactForm";
import ContactInfo from "@/components/ContactInfo";
import Navbar from "@/components/Navbar";
import NewsletterSection from "@/components/NewsletterSection";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title:       "Contact Us — Sastaghar",
  description:
    "Get in touch with the Sastaghar team for property inquiries, home loan assistance, or any questions. We respond within 24 hours.",
  openGraph: {
    title:       "Contact Sastaghar",
    description: "Reach out to our property experts. We're here to help you find your dream home.",
    url:         "https://sastaghar.com/contact",
    siteName:    "Sastaghar",
    type:        "website",
  },
};

export default function ContactPage() {
  return (
    <main className="min-h-screen">
    <Navbar />
      {/* ── Section 1: Contact form + image ───────────────── */}
      <ContactForm />

      {/* ── Section 2: Address + social + map ─────────────── */}
      <ContactInfo />

      <NewsletterSection />
      <Footer />
    </main>
  );
}

// ============================================================
// FILE PLACEMENT GUIDE
// ============================================================
//
// app/
//   contact/
//     page.tsx                   ← this file
//
// components/
//   contact/
//     ContactForm.tsx            ← form + image section
//     ContactInfo.tsx            ← address + map section
//
// app/
//   api/
//     contact/
//       route.ts                 ← API handler (save + email)
//
// ============================================================
// ENVIRONMENT VARIABLES NEEDED (.env.local)
// ============================================================
//
// # Supabase (already set up)
// NEXT_PUBLIC_SUPABASE_URL=https://xxxx.supabase.co
// SUPABASE_SERVICE_ROLE_KEY=eyJ...
//
// # Resend
// RESEND_API_KEY=re_xxxxxxxxxxxxxxxxxxxx
// RESEND_FROM_EMAIL=noreply@sastaghar.com
// ADMIN_CONTACT_EMAIL=vinay@vindhyaenterprises.com
//
// ============================================================
// RESEND SETUP STEPS (if not done yet)
// ============================================================
//
// 1. Go to resend.com → sign up
// 2. Dashboard → API Keys → Create API Key → copy it
// 3. Dashboard → Domains → Add Domain → add sastaghar.com
//    (Add the DNS records it shows you in your domain provider)
//    This lets you send FROM noreply@sastaghar.com
//    (While verifying, you can use onboarding@resend.dev as FROM
//     and still receive at any TO address)
// 4. Set all three env vars above
// 5. The route.ts handles the rest automatically
//
// ============================================================
// SUPABASE TABLE (already created by you)
// ============================================================
//
// create table public.contact (
//   id         bigint generated by default as identity not null,
//   created_at timestamp with time zone not null default now(),
//   name       text null,
//   email      text null,
//   message    text null,
//   constraint contact_pkey primary key (id)
// );
//
// One thing to add — RLS policy so the API route can insert:
// (The service role key bypasses RLS so this isn't strictly
//  needed, but good practice to be explicit)
//
// alter table public.contact enable row level security;
//
// create policy "contact_service_role_insert"
//   on public.contact
//   for insert
//   with check (true);
//   -- Service role always bypasses RLS anyway,
//   -- but this documents the intent clearly.
//
// ============================================================